ES6 syntax update.
maximsmol/node2html pull request #1
Opened 2019-03-26 11:19 UTC by b3none

Changes:
- Everything is now ES6
- Bumped to `2.0.0` since some versions of node are not ES6 compatible.

2019-03-28 23:42 UTC, maximsmol requested changes
Did some review in case you get bored again lol. If you don't plan on working on this further, I'll merge it in as-is because this is still obviously much better than ES3.

2019-03-28 23:42 UTC, maximsmol commented on lib/node2html.js
> +const Parser = add => this.addToResult = add;
Should be an actual class if we are going fully ES6.

2019-03-28 23:42 UTC, maximsmol commented on lib/node2html.js
> +			 if (
This is now really unreadable imo. I don't see the problem with typing out `continue` a few times as in the old version. Right now this just looks confusing because it's a "one-line" `if` (which is how I read it since it has a single instruction for the body), but it takes up a whopping 6 lines. Additionally, the condition is really long and doesn't really show the parallel structure better (which I assume was the intent of this change in the first place). It still has to list the `doctype` tests separately, because they are the only two things that really have any semantic relation to each other, but now there is also much more line noise in the form of the parenthesis and the fact that every line has to start with a `||`.

2019-03-28 23:42 UTC, maximsmol commented on lib/node2html.js
> +			 	(el[j].indexOf('$') !== 0)
For ES6: `indexOf == 0` -> `startsWith`. https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/startsWith

2019-03-28 23:42 UTC, maximsmol commented on lib/node2html.js
> +	let isHtml = key.indexOf('html') === 0;
For ES6: `indexOf == 0` -> `startsWith`. https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/startsWith

2019-03-28 23:42 UTC, maximsmol commented on lib/node2html.js
> +	let found = /(\w+)(?:#([\w-]+))?((?:\.[\w-]+)*)?/ig.exec(key);
Should be `const`.

2019-03-28 23:42 UTC, maximsmol commented on lib/node2html.js
> +	let selector = this.parseSelector(key);
Should be `const`.

2019-03-28 23:42 UTC, maximsmol commented on lib/node2html.js
> +				let toUnpack = el[i + 1];
Should be `const`.

2019-03-28 23:42 UTC, maximsmol commented on lib/node2html.js
> +			if (el[i].indexOf('$') === 0) {
For ES6: `indexOf == 0` -> `startsWith`. https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/startsWith

2019-03-28 23:42 UTC, maximsmol commented on lib/node2html.js
> +	if (Parser.shouldNotClose.indexOf(selector.tag) === -1) {
For ES6: `indexOf == -1` -> `!contains`. https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/includes

2019-03-28 23:42 UTC, maximsmol commented on lib/node2html.js
> +		if (data[i].indexOf('html') === 0) {
For ES6: `indexOf == 0` -> `startsWith`. https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/startsWith

2019-03-28 23:42 UTC, maximsmol commented on lib/node2html.js
> +	let res = '';
Should be `const`.

2019-03-28 23:42 UTC, maximsmol commented on lib/node2html.js
> +	let p = new Parser(data => res += data);
Should be `const`.

2019-03-28 23:42 UTC, maximsmol commented on lib/node2html.js
> +const Node2HtmlStream = (tree, options) => {
Should be an actual class.

2019-03-28 23:42 UTC, maximsmol commented on lib/node2html.js
>  util.inherits(Node2HtmlStream, stream.Readable);
Should be an actual `extends`.

2019-03-28 23:42 UTC, maximsmol commented on lib/node2html.js
> +		let p = new Parser(data => self._res += data);
Should be `const`.

2019-03-28 23:42 UTC, maximsmol commented on lib/node2html.js
> +		let self = this;
Should be `const`.

2019-03-28 23:42 UTC, maximsmol commented on lib/node2html.js
> +module.exports = {
Should be actual `export`s.

2019-03-29 11:46 UTC, b3none commented on lib/node2html.js
> +			 if (
Since this: `if (el[j].startsWith('$')) {` will catch the rest of the cases defined I've stripped away the others.

2019-03-29 11:49 UTC, b3none commented on lib/node2html.js
> +	let res = '';
No `res += data`

2019-03-29 15:44 UTC, maximsmol approved these changes
All good now :)

2019-03-29 15:44 UTC, merged